### ISSUE TITLE
Can't reach Google right now (Speech Recognizer Problem?)

### ISSUE THREAD

**Issue by ghost** [zhuowei/Xenologer#23]
Hello,

When I say "google" or "get directions to", the glass app tells me "Can't reach Google right now" but I'm sure there's nothing wrong about the network. I checked the logcat and saw messages below:

D/RecognizerController: onReadyForSpeech
E/RecognizerController: onError
E/RecognizerController: com.google.android.speech.embedded.Greco3RecognitionEngine$EmbeddedRecognizerUnavailableException: Embedded recognizer unavailable
E/RecognizerController:  at com.google.android.speech.embedded.Greco3RecognitionEngine.startRecognition(Greco3RecognitionEngine.java:104)

Please help.
Thanks.

**Comment by BramRausch** [comment]
same problem here :(

**Comment by Androguide** [comment]
Looks like you did not set your account properly.
Did you go past the QR code verification (by hitting enter in the GlassSetup app while connected to http://googl.com/myglass on the QR code page) ?
This should fix the problem and allow you to enable Glasswares

**Comment by BramRausch** [comment]
But as i hit enter it removes my account from phone and crashes

**Comment by ChristianFJung** [comment]
@Androguide  I went through setup and still have connection issue, @zhuowei  any new changes?

**Comment by sinedied** [comment]
Still with this same problem: tried v5, v6 and v7 versions, on both Nexus 4 and Galaxy Gear, same result :(

**Comment by vaibhavbparikh** [comment]
I tried with variety of devices but problem persist , one more thing glass camera also gets crashed when i tried to set up wifi with QR Code option
